name: CI

# credit: https://github.com/vlang/vsl/blob/master/.github/workflows/ci.yml

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            make: make
            bin: ./v
          - name: macos-latest
            make: make
            bin: ./v
          - name: windows-latest
            make: .\make.bat
            bin: ./v.exe

    steps:
      - name: Build V and symlink
        run: |
          cd ..
          git clone https://github.com/vlang/v.git --depth 1 v
          cd v
          make
          ./v symlink -githubci

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2
      - name: V doctor
        run: v doctor
      - name: Build ${{ github.event.repository.name }}
        run:  make prod
      - name: Build doc
        run:  make doc
      - name: Run Tests
        run: make test
