name: CI

# credit: https://github.com/vlang/vsl/blob/master/.github/workflows/ci.yml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor
      - name: Build ${{ github.event.repository.name }}
        run:  make prod
      - name: Build doc
        run:  make doc
      - name: Run Tests
        run: make test
