name: CI

# credit: https://github.com/vlang/vsl/blob/master/.github/workflows/ci.yml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build V and symlink
        run: |
          cd ..
          git clone https://github.com/vlang/v.git --depth 1 v
          cd v
          make
          ./v symlink -githubci

      - name: V doctor
        run: v doctor
      - name: Build ${{ github.event.repository.name }}
        run:  make prod
      - name: Build doc
        run:  make doc
      - name: Run Tests
        run: make test
